from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd + '/../include']

if  GetDepend(['RT_USING_SERIAL_V1']):
    src = Glob('serial.c')
    group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_SERIAL_V1'], CPPPATH = CPPPATH)
    
elif  GetDepend(['RT_USING_SERIAL_X']):
    src = Glob('serialX.c')
    group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_SERIAL_X'], CPPPATH = CPPPATH)

Return('group')
